/*
 * This file is generated by jOOQ.
 */
package org.opentaint.ir.impl.storage.ers.jooq.tables.references

import org.opentaint.ir.impl.storage.ers.jooq.tables.Types

/**
 * The table <code>Types</code>.
 */
val TYPES = Types.TYPES
