/*
 * This file is generated by jOOQ.
 */
package org.opentaint.ir.impl.storage.jooq

import org.jooq.Schema
import org.jooq.impl.CatalogImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        val DEFAULT_CATALOG = org.opentaint.ir.impl.storage.jooq.DefaultCatalog()
    }

    /**
     * The schema <code>DEFAULT_SCHEMA</code>.
     */
    val DEFAULT_SCHEMA get() = org.opentaint.ir.impl.storage.jooq.DefaultSchema.Companion.DEFAULT_SCHEMA

    override fun getSchemas(): List<Schema> = listOf(
        org.opentaint.ir.impl.storage.jooq.DefaultSchema.Companion.DEFAULT_SCHEMA
    )
}
