passThrough:
- function: javax.script.Bindings#get
  signature: (java.lang.Object) java.lang.Object
  copy:
  - from:
    - this
    - .java.util.Map#<rule-storage>#java.lang.Object
    to: result
  - from:
    - this
    - .javax.script.Bindings#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.ScriptEngineFactory#getOutputStatement
  signature: (java.lang.String) java.lang.String
  copy:
  - from: arg(*)
    to: result
- function: javax.script.AbstractScriptEngine#getScriptContext
  signature: (javax.script.Bindings) javax.script.ScriptContext
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.ScriptContext#getAttribute
  signature:
    return: java.lang.Object
  copy:
  - from:
    - this
    - .javax.script.ScriptContext#attribute#java.lang.Object
    to: result
  - from:
    - this
    - .javax.script.ScriptContext#attribute#java.lang.Object
    to: result
- function: javax.script.Bindings#putAll
  signature: (java.util.Map) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.util.Map#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.script.Bindings#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: javax.script.AbstractScriptEngine#getScriptContext
  signature: (javax.script.Bindings) javax.script.ScriptContext
  copy:
  - from:
    - this
    - .javax.script.AbstractScriptEngine#<rule-storage>#java.lang.Object
    to: result
  - from:
    - this
    - .javax.script.ScriptEngine#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.ScriptEngineFactory#getProgram
  signature: (java.lang.String[]) java.lang.String
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: result
- function: javax.script.ScriptContext#setAttribute
  signature: (java.lang.String, java.lang.Object, int) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.script.ScriptEngine#setBindings
  signature:
    params:
    - index: 0
      type: javax.script.Bindings
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptEngine#bindings#javax.script.Bindings
- function: javax.script.Bindings#remove
  signature: (java.lang.Object) java.lang.Object
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.AbstractScriptEngine#<init>
  signature: (javax.script.Bindings) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.script.AbstractScriptEngine#getContext
  signature: () javax.script.ScriptContext
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.ScriptEngineManager#getBindings
  signature: () javax.script.Bindings
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.Bindings#get
  signature: (java.lang.Object) java.lang.Object
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.ScriptContext#getBindings
  signature: (int) javax.script.Bindings
  copy:
  - from:
    - this
    - .javax.script.ScriptContext#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.ScriptContext#setBindings
  signature:
    params:
    - index: 0
      type: javax.script.Bindings
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
- function: javax.script.ScriptEngineManager#setBindings
  signature:
    params:
    - index: 0
      type: javax.script.Bindings
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptEngineManager#globalBindings#javax.script.Bindings
- function: javax.script.ScriptEngineManager#setBindings
  signature: (javax.script.Bindings) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptEngineManager#<rule-storage>#java.lang.Object
- function: javax.script.ScriptContext#getAttribute
  signature: (java.lang.String, int) java.lang.Object
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.Bindings#put
  signature: (java.lang.Object, java.lang.Object) java.lang.Object
  copy:
  - from: arg(1)
    to:
    - this
    - .java.util.Map#<rule-storage>#java.lang.Object
  - from: arg(1)
    to:
    - this
    - .javax.script.Bindings#<rule-storage>#java.lang.Object
  - from: arg(1)
    to: this
- function: javax.script.AbstractScriptEngine#<init>
  signature: (javax.script.Bindings) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptEngine#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.script.AbstractScriptEngine#<rule-storage>#java.lang.Object
- function: javax.script.Bindings#remove
  signature: (java.lang.Object) java.lang.Object
  copy:
  - from:
    - this
    - .java.util.Map#<rule-storage>#java.lang.Object
    to: result
  - from:
    - this
    - .javax.script.Bindings#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.ScriptContext#getAttribute
  signature: (java.lang.String, int) java.lang.Object
  copy:
  - from:
    - this
    - .javax.script.ScriptContext#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.Bindings#put
  signature: (java.lang.String, java.lang.Object) java.lang.Object
  copy:
  - from: arg(1)
    to:
    - this
    - .java.util.Map#<rule-storage>#java.lang.Object
  - from: arg(1)
    to:
    - this
    - .javax.script.Bindings#<rule-storage>#java.lang.Object
  - from: arg(1)
    to: this
- function: javax.script.ScriptContext#setAttribute
  signature: (java.lang.String, java.lang.Object, int) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptContext#<rule-storage>#java.lang.Object
- function: javax.script.ScriptEngineManager#getBindings
  signature: () javax.script.Bindings
  copy:
  - from:
    - this
    - .javax.script.ScriptEngineManager#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.AbstractScriptEngine#getContext
  signature: () javax.script.ScriptContext
  copy:
  - from:
    - this
    - .javax.script.AbstractScriptEngine#<rule-storage>#java.lang.Object
    to: result
  - from:
    - this
    - .javax.script.ScriptEngine#<rule-storage>#java.lang.Object
    to: result
  - from:
    - this
    - .javax.script.AbstractScriptEngine#bindings#javax.script.Bindings
    to:
    - result
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
  - from:
    - this
    - .javax.script.AbstractScriptEngine#context#javax.script.ScriptContext
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
    to:
    - result
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
- function: javax.script.ScriptContext#removeAttribute
  signature: (java.lang.String, int) java.lang.Object
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.ScriptEngine#setBindings
  signature: (javax.script.Bindings, int) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.script.ScriptContext#getAttribute
  signature: (java.lang.String) java.lang.Object
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.ScriptEngineManager#setBindings
  signature: (javax.script.Bindings) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.script.ScriptEngine#setBindings
  signature: (javax.script.Bindings, int) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptEngine#<rule-storage>#java.lang.Object
- function: javax.script.ScriptContext#removeAttribute
  signature: (java.lang.String, int) java.lang.Object
  copy:
  - from:
    - this
    - .javax.script.ScriptContext#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.ScriptContext#getAttribute
  signature: (java.lang.String) java.lang.Object
  copy:
  - from:
    - this
    - .javax.script.ScriptContext#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.ScriptEngine#getBindings
  signature:
    return: javax.script.Bindings
  copy:
  - from:
    - this
    - .javax.script.ScriptEngine#bindings#javax.script.Bindings
    to: result
- function: javax.script.ScriptEngine#getBindings
  signature: (int) javax.script.Bindings
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.ScriptEngineFactory#getMethodCallSyntax
  signature: (java.lang.String, java.lang.String, java.lang.String[]) java.lang.String
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: result
- function: javax.script.AbstractScriptEngine#getScriptContext
  signature: (*) javax.script.ScriptContext
  copy:
  - from:
    - this
    - .javax.script.AbstractScriptEngine#bindings#javax.script.Bindings
    to:
    - result
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
  - from:
    - this
    - .javax.script.AbstractScriptEngine#context#javax.script.ScriptContext
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
    to:
    - result
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
- function: javax.script.ScriptContext#getBindings
  signature: (int) javax.script.Bindings
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.script.ScriptEngineManager#getBindings
  signature:
    return: javax.script.Bindings
  copy:
  - from:
    - this
    - .javax.script.ScriptEngineManager#globalBindings#javax.script.Bindings
    to: result
- function: javax.script.AbstractScriptEngine#getContext
  signature:
    return: javax.script.ScriptContext
  copy:
  - from:
    - this
    - .javax.script.AbstractScriptEngine#context#javax.script.ScriptContext
    to: result
- function: javax.script.AbstractScriptEngine#<init>
  signature:
    params:
    - index: 0
      type: javax.script.Bindings
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.AbstractScriptEngine#bindings#javax.script.Bindings
  - from: arg(0)
    to:
    - this
    - .javax.script.AbstractScriptEngine#context#javax.script.ScriptContext
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
- function: javax.script.AbstractScriptEngine#setContext
  signature: (javax.script.ScriptContext) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptEngine#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.script.AbstractScriptEngine#<rule-storage>#java.lang.Object
- function: javax.script.AbstractScriptEngine#setContext
  signature:
    params:
    - index: 0
      type: javax.script.ScriptContext
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.AbstractScriptEngine#context#javax.script.ScriptContext
- function: javax.script.SimpleBindings#<init>
  signature: (java.util.Map) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.util.Map#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.script.Bindings#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.script.SimpleBindings#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: javax.script.ScriptContext#setBindings
  signature: (javax.script.Bindings, int) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.script.ScriptContext#<rule-storage>#java.lang.Object
- function: javax.script.AbstractScriptEngine#getScriptContext
  signature:
    return: javax.script.ScriptContext
  copy:
  - from:
    - this
    - .javax.script.AbstractScriptEngine#context#javax.script.ScriptContext
    to: result
- function: javax.script.ScriptContext#setBindings
  signature: (javax.script.Bindings, int) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.script.ScriptContext#getBindings
  signature:
    return: javax.script.Bindings
  copy:
  - from:
    - this
    - .javax.script.ScriptContext#bindings#javax.script.Bindings
    to: result
- function: javax.script.ScriptContext#removeAttribute
  signature:
    return: java.lang.Object
  copy:
  - from:
    - this
    - .javax.script.ScriptContext#attribute#java.lang.Object
    to: result
- function: javax.script.ScriptEngine#getBindings
  signature: (int) javax.script.Bindings
  copy:
  - from:
    - this
    - .javax.script.ScriptEngine#<rule-storage>#java.lang.Object
    to: result
- function: javax.script.AbstractScriptEngine#setContext
  signature: (javax.script.ScriptContext) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
