passThrough:
- function: javax.xml.namespace.QName#<init>
  signature: (java.lang.String) void
  copy:
  - from: arg(*)
    to:
    - this
    - .javax.xml.namespace.QName#<rule-storage>#java.lang.Object
- function: javax.xml.namespace.QName#<init>
  signature: (java.lang.String, java.lang.String) void
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
- function: javax.xml.namespace.QName#getPrefix
  signature: () java.lang.String
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.xml.namespace.QName#getPrefix
  signature: () java.lang.String
  copy:
  - from:
    - this
    - .javax.xml.namespace.QName#<rule-storage>#java.lang.Object
    to: result
- function: javax.xml.namespace.QName#valueOf
  signature: (java.lang.String) javax.xml.namespace.QName
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: result
- function: javax.xml.namespace.QName#<init>
  signature: (java.lang.String) void
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
- function: javax.xml.namespace.QName#getLocalPart
  signature:
    return: java.lang.String
  copy:
  - from:
    - this
    - .javax.xml.namespace.QName#localPart#java.lang.String
    to: result
- function: javax.xml.namespace.QName#getNamespaceURI
  signature: () java.lang.String
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.xml.namespace.QName#getNamespaceURI
  signature: () java.lang.String
  copy:
  - from:
    - this
    - .javax.xml.namespace.QName#<rule-storage>#java.lang.Object
    to: result
- function: javax.xml.namespace.QName#valueOf
  signature:
    params:
    - index: 0
      type: java.lang.String
    return: javax.xml.namespace.QName
  copy:
  - from: arg(0)
    to:
    - result
    - .javax.xml.namespace.QName#localPart#java.lang.String
- function: javax.xml.namespace.QName#getPrefix
  signature:
    return: java.lang.String
  copy:
  - from:
    - this
    - .javax.xml.namespace.QName#localPart#java.lang.String
    to: result
- function: javax.xml.namespace.QName#getLocalPart
  signature: () java.lang.String
  copy:
  - from:
    - this
    - .javax.xml.namespace.QName#<rule-storage>#java.lang.Object
    to: result
- function: javax.xml.namespace.QName#<init>
  signature:
    params:
    - index: 0
      type: java.lang.String
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.namespace.QName#localPart#java.lang.String
  - from: arg(0)
    to:
    - this
    - .javax.xml.namespace.QName#localPart#java.lang.String
  - from: arg(0)
    to:
    - this
    - .javax.xml.namespace.QName#localPart#java.lang.String
- function: javax.xml.namespace.QName#getNamespaceURI
  signature:
    return: java.lang.String
  copy:
  - from:
    - this
    - .javax.xml.namespace.QName#localPart#java.lang.String
    to: result
- function: javax.xml.namespace.QName#<init>
  signature: (java.lang.String, java.lang.String) void
  copy:
  - from: arg(*)
    to:
    - this
    - .javax.xml.namespace.QName#<rule-storage>#java.lang.Object
- function: javax.xml.namespace.QName#<init>
  signature: (java.lang.String, java.lang.String, java.lang.String) void
  copy:
  - from: arg(*)
    to:
    - this
    - .javax.xml.namespace.QName#<rule-storage>#java.lang.Object
- function: javax.xml.namespace.QName#getLocalPart
  signature: () java.lang.String
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.xml.namespace.QName#<init>
  signature: (java.lang.String, java.lang.String, java.lang.String) void
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
