passThrough:
- function: javax.xml.transform.sax.SAXSource#setInputSource
  signature: (org.xml.sax.InputSource) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function:
    package: javax.xml.transform.sax
    class: SAXResult
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXResult#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.Result#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXSource#getXMLReader
  signature: () org.xml.sax.XMLReader
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
- function: javax.xml.transform.sax.SAXResult#setLexicalHandler
  signature: (org.xml.sax.ext.LexicalHandler) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.xml.transform.sax.SAXResult#getLexicalHandler
  signature: () org.xml.sax.ext.LexicalHandler
  copy:
  - from:
    - this
    - .javax.xml.transform.sax.SAXResult#<rule-storage>#java.lang.Object
    to: result
  - from:
    - this
    - .javax.xml.transform.Result#<rule-storage>#java.lang.Object
    to: result
- function: javax.xml.transform.sax.SAXSource#<init>
  signature: (org.xml.sax.InputSource) void
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
- function: javax.xml.transform.sax.SAXResult#setLexicalHandler
  signature:
    params:
    - index: 0
      type: org.xml.sax.ext.LexicalHandler
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXResult#lexicalHandler#org.xml.sax.ext.LexicalHandler
- function: javax.xml.transform.sax.SAXResult#setHandler
  signature: (org.xml.sax.ContentHandler) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function:
    package: javax.xml.transform.sax
    class: SAXResult
    name:
      pattern: <init>
  signature:
    params:
    - index: 0
      type: org.xml.sax.ContentHandler
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXResult#contentHandler#org.xml.sax.ContentHandler
- function: javax.xml.transform.sax.SAXSource#sourceToInputSource
  signature: (javax.xml.transform.Source) org.xml.sax.InputSource
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: result
- function: javax.xml.transform.sax.SAXResult#getHandler
  signature: () org.xml.sax.ContentHandler
  copy:
  - from:
    - this
    - .javax.xml.transform.sax.SAXResult#<rule-storage>#java.lang.Object
    to: result
  - from:
    - this
    - .javax.xml.transform.Result#<rule-storage>#java.lang.Object
    to: result
- function: javax.xml.transform.sax.SAXResult#getLexicalHandler
  signature: () org.xml.sax.ext.LexicalHandler
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function:
    package: javax.xml.transform.sax
    class: SAXResult
    name:
      pattern: <init>
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.xml.transform.sax.SAXSource#getInputSource
  signature: () org.xml.sax.InputSource
  copy:
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.Source#<rule-storage>#java.lang.Object
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXSource#setInputSource
  signature:
    params:
    - index: 0
      type: org.xml.sax.InputSource
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#inputSource#org.xml.sax.InputSource
- function: javax.xml.transform.sax.SAXSource#setInputSource
  signature: (org.xml.sax.InputSource) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.Source#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXSource#<init>
  signature: (org.xml.sax.InputSource) void
  copy:
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.Source#<rule-storage>#java.lang.Object
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXSource#setXMLReader
  signature: (org.xml.sax.XMLReader) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.xml.transform.sax.SAXResult#getHandler
  signature:
    return: org.xml.sax.ContentHandler
  copy:
  - from:
    - this
    - .javax.xml.transform.sax.SAXResult#contentHandler#org.xml.sax.ContentHandler
    to: result
- function: javax.xml.transform.sax.SAXSource#setXMLReader
  signature:
    params:
    - index: 0
      type: org.xml.sax.XMLReader
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#xmlReader#org.xml.sax.XMLReader
- function: javax.xml.transform.sax.SAXSource#getInputSource
  signature: () org.xml.sax.InputSource
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
- function: javax.xml.transform.sax.SAXSource#<init>
  signature: (org.xml.sax.XMLReader, org.xml.sax.InputSource) void
  copy:
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.Source#<rule-storage>#java.lang.Object
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXResult#getHandler
  signature: () org.xml.sax.ContentHandler
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.xml.transform.sax.SAXSource#<init>
  signature: () void
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
- function: javax.xml.transform.sax.SAXResult#setHandler
  signature: (org.xml.sax.ContentHandler) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXResult#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.Result#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXSource#<init>
  signature: (org.xml.sax.XMLReader, org.xml.sax.InputSource) void
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
- function: javax.xml.transform.sax.SAXSource#<init>
  signature:
    params:
    - index: 0
      type: org.xml.sax.XMLReader
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#xmlReader#org.xml.sax.XMLReader
- function: javax.xml.transform.sax.SAXSource#setXMLReader
  signature: (org.xml.sax.XMLReader) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.Source#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXResult#getLexicalHandler
  signature:
    return: org.xml.sax.ext.LexicalHandler
  copy:
  - from:
    - this
    - .javax.xml.transform.sax.SAXResult#lexicalHandler#org.xml.sax.ext.LexicalHandler
    to: result
- function: javax.xml.transform.sax.SAXResult#setLexicalHandler
  signature: (org.xml.sax.ext.LexicalHandler) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXResult#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.Result#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXSource#getXMLReader
  signature: () org.xml.sax.XMLReader
  copy:
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.Source#<rule-storage>#java.lang.Object
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXSource#<init>
  signature: () void
  copy:
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.Source#<rule-storage>#java.lang.Object
  - from: arg(*)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#<rule-storage>#java.lang.Object
- function: javax.xml.transform.sax.SAXSource#<init>
  signature:
    params:
    - index: 0
      type: org.xml.sax.InputSource
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXSource#inputSource#org.xml.sax.InputSource
- function: javax.xml.transform.sax.SAXResult#setHandler
  signature:
    params:
    - index: 0
      type: org.xml.sax.ContentHandler
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.xml.transform.sax.SAXResult#contentHandler#org.xml.sax.ContentHandler
