passThrough:
- function: java.security.interfaces.RSAMultiPrimePrivateCrtKey#getOtherPrimeInfo
  signature: () java.security.spec.RSAOtherPrimeInfo[]
  taintCopyOnly: true
  copy:
  - from: this
    to: result
