passThrough:
- function: javax.sql.rowset.serial.SerialDatalink#<init>
  signature: (java.net.URL) void
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: javax.sql.rowset.serial.SerialDatalink#getDatalink
  signature: () java.net.URL
  copy:
  - from:
    - this
    - .javax.sql.rowset.serial.SerialDatalink#<rule-storage>#java.lang.Object
    to: result
- function: javax.sql.rowset.serial.SerialDatalink#<init>
  signature:
    params:
    - index: 0
      type: java.net.URL
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.sql.rowset.serial.SerialDatalink#url#java.net.URL
- function: javax.sql.rowset.serial.SerialJavaObject#getFields
  signature: () java.lang.reflect.Field[]
  copy:
  - from:
    - this
    - .javax.sql.rowset.serial.SerialJavaObject#<rule-storage>#java.lang.Object
    to: result
- function: javax.sql.rowset.serial.SerialDatalink#getDatalink
  signature: () java.net.URL
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.sql.rowset.serial.SerialDatalink#<init>
  signature: (java.net.URL) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.sql.rowset.serial.SerialDatalink#<rule-storage>#java.lang.Object
- function: javax.sql.rowset.serial.SerialJavaObject#getObject
  signature:
    return: java.lang.Object
  copy:
  - from:
    - this
    - .javax.sql.rowset.serial.SerialJavaObject#wrappedObject#java.lang.Object
    to: result
- function: javax.sql.rowset.serial.SerialDatalink#getDatalink
  signature:
    return: java.net.URL
  copy:
  - from:
    - this
    - .javax.sql.rowset.serial.SerialDatalink#url#java.net.URL
    to: result
- function: javax.sql.rowset.serial.SerialJavaObject#getObject
  signature: () java.lang.Object
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.sql.rowset.serial.SerialJavaObject#getFields
  signature: () java.lang.reflect.Field[]
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: javax.sql.rowset.serial.SerialJavaObject#getObject
  signature: () java.lang.Object
  copy:
  - from:
    - this
    - .javax.sql.rowset.serial.SerialJavaObject#<rule-storage>#java.lang.Object
    to: result
- function: javax.sql.rowset.serial.SerialJavaObject#<init>
  signature: (java.lang.Object) void
  copy:
  - from: arg(0)
    to:
    - this
    - .javax.sql.rowset.serial.SerialJavaObject#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
