library: javax.servlet.jsp:javax.servlet.jsp-api:2.3.3
dependencies:
- javax.servlet:javax.servlet-api:4.0.1
passThrough:
- function: javax.servlet.jsp.JspWriter#print
  signature: (long) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspFactory#getPageContext
  signature: (javax.servlet.Servlet, javax.servlet.ServletRequest, javax.servlet.ServletResponse,
    java.lang.String, boolean, int, boolean) javax.servlet.jsp.PageContext
  copy:
  - from: arg(2)
    to: result
  - from: arg(1)
    to: result
- function: javax.servlet.jsp.JspWriter#print
  signature: (char[]) void
  copy:
  - from:
    - arg(0)
    - '[*]'
    to: this
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from:
    - arg(0)
    - '[*]'
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
  - from:
    - arg(0)
    - '[*]'
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from:
    - arg(0)
    - '[*]'
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (char[]) void
  copy:
  - from:
    - arg(0)
    - '[*]'
    to: this
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from:
    - arg(0)
    - '[*]'
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
  - from:
    - arg(0)
    - '[*]'
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from:
    - arg(0)
    - '[*]'
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#print
  signature: (java.lang.String) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (boolean) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: () void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (double) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (int) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#print
  signature: (char) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#print
  signature: (java.lang.Object) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#print
  signature: (double) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#print
  signature: (int) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (java.lang.String) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (long) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (char) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (java.lang.Object) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#println
  signature: (float) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#print
  signature: (boolean) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
- function: javax.servlet.jsp.JspWriter#print
  signature: (float) void
  copy:
  - from: arg(0)
    to:
    - this
    - .java.io.Writer#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .java.lang.Appendable#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .javax.servlet.jsp.JspWriter#<rule-storage>#java.lang.Object
