library: io.netty:netty-common:4.2.9.Final
passThrough:
- function: io.netty.util.ReferenceCounted#touch
  copy:
  - from: this
    to: result
- function: io.netty.util.ReferenceCounted#retain
  copy:
  - from: this
    to: result
