library: org.apache.httpcomponents:httpclient:4.5.14
passThrough:
- function: org.apache.http.client.utils.URIBuilder#getQueryParams
  copy:
  - from: this
    to: result
- function: org.apache.http.auth.AuthScheme#authenticate
  copy:
  - from: arg(0)
    to: result
- function:
    package: org.apache.http.client.methods
    class: HttpPut
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpPut#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.impl.client.DefaultHttpClient#<init>
  signature:
    params:
    - index: 0
      type: org.apache.http.conn.ClientConnectionManager
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.impl.client.DefaultHttpClient#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.utils.URIBuilder#toString
  copy:
  - from: this
    to: result
- function: org.apache.http.client.methods.HttpRequestBase#setURI
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpRequestBase#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.utils.URIBuilder#setParameter
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.client.utils.CloneUtils#cloneObject
  copy:
  - from: arg(0)
    to: result
- function:
    package: org.apache.http.client.methods
    class: HttpGet
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpGet#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.conn.ssl.SSLSocketFactory#<init>
  signature:
    params:
    - index: 0
      type: javax.net.ssl.SSLSocketFactory
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.conn.ssl.SSLSocketFactory#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.utils.URIBuilder#setQuery
  copy:
  - from: arg(0)
    to: result
- function:
    package: org.apache.http.client.methods
    class: HttpTrace
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpTrace#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.methods.HttpDelete#setURI
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpDelete#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.methods.HttpRequestBase#toString
  copy:
  - from: this
    to: result
  - from:
    - this
    - .org.apache.http.client.methods.HttpRequestBase#<rule-storage>#java.lang.Object
    to: result
- function: org.apache.http.client.utils.URIBuilder#addParameters
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.client.methods.HttpUriRequest#getURI
  copy:
  - from: this
    to: result
- function: org.apache.http.client.methods.HttpGet#setURI
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpGet#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.cookie.Cookie#getPath
  copy:
  - from: this
    to: result
- function: org.apache.http.client.utils.URIBuilder#setCustomQuery
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.client.methods.HttpHead#setURI
  copy:
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpHead#<rule-storage>#java.lang.Object
- function: org.apache.http.client.utils.URIBuilder#addParameter
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.client.CredentialsProvider#setCredentials
  copy:
  - from: arg(1)
    to:
    - this
    - .org.apache.http.client.CredentialsProvider#<rule-storage>#java.lang.Object
  - from: arg(1)
    to: this
- function: org.apache.http.conn.scheme.SchemeRegistry#setItems
  copy:
  - from: arg(0)
    to: result
  - from: arg(0)
    to:
    - this
    - .org.apache.http.conn.scheme.SchemeRegistry#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function:
    package: org.apache.http.client.methods
    class: HttpOptions
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpOptions#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function:
    package: org.apache.http.client.methods
    class: HttpDelete
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpDelete#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.cookie.Cookie#getComment
  copy:
  - from: this
    to: result
- function: org.apache.http.client.utils.URIBuilder#build
  copy:
  - from: this
    to: result
- function: org.apache.http.client.utils.URIBuilder#setParameters
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.conn.scheme.Scheme#<init>
  signature:
    params:
    - index: 0
      type: java.lang.String
    - index: 1
      type: org.apache.http.conn.scheme.SocketFactory
    - index: 2
      type: int
  copy:
  - from: arg(1)
    to:
    - this
    - .org.apache.http.conn.scheme.Scheme#<rule-storage>#java.lang.Object
  - from: arg(1)
    to: this
- function: org.apache.http.cookie.Cookie#getCommentURL
  copy:
  - from: this
    to: result
- function: org.apache.http.cookie.Cookie#getName
  copy:
  - from: this
    to: result
- function:
    package: org.apache.http.client.methods
    class: HttpHead
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpHead#<rule-storage>#java.lang.Object
- function: org.apache.http.client.utils.URIBuilder#setPath
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.client.utils.URIBuilder#getPath
  copy:
  - from: this
    to: result
- function: org.apache.http.cookie.Cookie#getDomain
  copy:
  - from: this
    to: result
- function: org.apache.http.client.utils.URIBuilder#setHost
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.cookie.Cookie#getExpiryDate
  copy:
  - from: this
    to: result
- function: org.apache.http.auth.ContextAwareAuthScheme#authenticate
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.client.utils.URIBuilder#getHost
  copy:
  - from: this
    to: result
- function: org.apache.http.conn.ClientConnectionManager#<init>
  signature:
    params:
    - index: 0
      type: org.apache.http.conn.scheme.SchemeRegistry
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.conn.ClientConnectionManager#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.methods.HttpPut#setURI
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpPut#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.methods.HttpPost#setURI
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpPost#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.utils.CloneUtils#clone
  copy:
  - from: arg(0)
    to: result
- function: org.apache.http.cookie.Cookie#getValue
  copy:
  - from: this
    to: result
- function: org.apache.http.conn.scheme.SchemeRegistry#register
  copy:
  - from: arg(0)
    to: result
  - from: arg(0)
    to:
    - this
    - .org.apache.http.conn.scheme.SchemeRegistry#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.methods.HttpOptions#setURI
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpOptions#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.cookie.Cookie#toString
  copy:
  - from: this
    to: result
- function: org.apache.http.client.methods.HttpRequestBase#getRequestLine
  copy:
  - from: this
    to: result
  - from:
    - this
    - .org.apache.http.client.methods.HttpRequestBase#<rule-storage>#java.lang.Object
    to: result
- function:
    package: org.apache.http.client.methods
    class: HttpPatch
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpPatch#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.methods.HttpPatch#setURI
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpPatch#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.utils.URIBuilder#setPort
  signature: (int) *
  copy:
  - from: this
    to: result
- function: org.apache.http.conn.ClientConnectionManager#<init>
  signature:
    params:
    - index: 0
      type: org.apache.http.params.HttpParams
    - index: 1
      type: org.apache.http.conn.scheme.SchemeRegistry
  copy:
  - from: arg(1)
    to:
    - this
    - .org.apache.http.conn.ClientConnectionManager#<rule-storage>#java.lang.Object
  - from: arg(1)
    to: this
- function:
    package: org.apache.http.client.methods
    class: HttpPost
    name:
      pattern: <init>
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpPost#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
- function: org.apache.http.client.methods.HttpTrace#setURI
  copy:
  - from: arg(0)
    to:
    - this
    - .org.apache.http.client.methods.HttpTrace#<rule-storage>#java.lang.Object
  - from: arg(0)
    to: this
