library: org.springframework:spring-jdbc:4.3.25.RELEASE
passThrough:
- function: org.springframework.jdbc.support.xml.SqlXmlObjectMappingHandler#newMarshallingSqlXmlValue
  copy:
  - from: arg(0)
    to: result
- function: org.springframework.jdbc.support.xml.SqlXmlObjectMappingHandler#getXmlAsObject
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: result
- function: org.springframework.jdbc.support.xml.SqlXmlObjectMappingHandler#getXmlAsObject
  signature:
    params:
    - index: 0
      type: java.sql.ResultSet
    return: java.lang.Object
  copy:
  - from:
    - arg(0)
    - .java.sql.ResultSet#columnValue#java.lang.Object
    to: result
  - from:
    - arg(0)
    - .java.sql.ResultSet#ref#java.sql.Ref
    - .java.sql.Ref#value#java.lang.Object
    to: result
