library: org.springframework.ws:spring-ws-core:4.1.0
dependencies:
- org.apache.ws.commons.axiom:axiom-api:1.4.0
passThrough:
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setSoapAction
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getEnvelope
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#<init>
  signature:
    params:
    - index: 0
      type: org.apache.axiom.soap.SOAPMessage
  taintCopyOnly: true
  copy:
  - from: arg(1)
    to: this
  - from: arg(2)
    to: this
  - from: arg(0)
    to: this
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setDocument
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setSoapAction
  copy:
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#<init>
  signature:
    params:
    - index: 2
      type: java.lang.String
  copy:
  - from: arg(2)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#soapAction#java.lang.String
  - from: arg(2)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#document#org.w3c.dom.Document
    - .org.w3c.dom.Document#documentElement#org.w3c.dom.Node
    - .org.w3c.dom.Node#nodeValue#java.lang.String
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setAxiomMessage
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getAttachment
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#<init>
  signature:
    params:
    - index: 0
      type: org.apache.axiom.soap.SOAPMessage
  copy:
  - from: arg(1)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
  - from: arg(2)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#axiomMessage#org.apache.axiom.soap.SOAPMessage
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getAttachments
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getAxiomMessage
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getEnvelope
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getDocument
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setSoapAction
  signature:
    params:
    - index: 0
      type: java.lang.String
  copy:
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#soapAction#java.lang.String
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#document#org.w3c.dom.Document
    - .org.w3c.dom.Document#documentElement#org.w3c.dom.Node
    - .org.w3c.dom.Node#nodeValue#java.lang.String
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setAxiomMessage
  signature:
    params:
    - index: 0
      type: org.apache.axiom.soap.SOAPMessage
  copy:
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#axiomMessage#org.apache.axiom.soap.SOAPMessage
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getSoapAction
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setDocument
  copy:
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setStreamingPayload
  copy:
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getDocument
  signature:
    return: org.w3c.dom.Document
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#document#org.w3c.dom.Document
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setAxiomMessage
  copy:
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getAttachment
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#<init>
  signature:
    params:
    - index: 1
      type: java.lang.String
  copy:
  - from: arg(1)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#soapAction#java.lang.String
  - from: arg(1)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#document#org.w3c.dom.Document
    - .org.w3c.dom.Document#documentElement#org.w3c.dom.Node
    - .org.w3c.dom.Node#nodeValue#java.lang.String
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getAxiomMessage
  signature:
    return: org.apache.axiom.soap.SOAPMessage
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#axiomMessage#org.apache.axiom.soap.SOAPMessage
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getAxiomMessage
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setStreamingPayload
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: this
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getAttachments
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getSoapAction
  signature:
    return: java.lang.String
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#soapAction#java.lang.String
    to: result
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#document#org.w3c.dom.Document
    - .org.w3c.dom.Document#documentElement#org.w3c.dom.Node
    - .org.w3c.dom.Node#nodeValue#java.lang.String
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getDocument
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#getSoapAction
  copy:
  - from:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#<rule-storage>#java.lang.Object
    to: result
- function: org.springframework.ws.soap.axiom.AxiomSoapMessage#setDocument
  signature:
    params:
    - index: 0
      type: org.w3c.dom.Document
  copy:
  - from: arg(0)
    to:
    - this
    - .org.springframework.ws.soap.axiom.AxiomSoapMessage#document#org.w3c.dom.Document
