library: org.springframework:spring-web:5.3.39
dependencies:
- commons-fileupload:commons-fileupload:1.5
passThrough:
- function: org.springframework.web.multipart.commons.CommonsMultipartFile#getFileItem
  signature:
    return: org.apache.commons.fileupload.FileItem
  copy:
  - from:
    - this
    - .org.springframework.web.multipart.commons.CommonsMultipartFile#fileItem#org.apache.commons.fileupload.FileItem
    to: result
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#getMultipartParameters
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#<init>
  copy:
  - from: arg(*)
    to:
    - this
    - .org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#<rule-storage>#java.lang.Object
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#getMultipartParameters
  copy:
  - from:
    - this
    - .org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#<rule-storage>#java.lang.Object
    to: result
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#<init>
  signature:
    params:
    - index: 0
      type: org.springframework.util.MultiValueMap
  copy:
  - from: arg(0)
    to:
    - this
    - .org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#multipartParameters#org.springframework.util.MultiValueMap
- function: org.springframework.web.multipart.commons.CommonsMultipartFile#getFileItem
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#getMultipartFiles
  taintCopyOnly: true
  copy:
  - from: this
    to: result
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#<init>
  taintCopyOnly: true
  copy:
  - from: arg(*)
    to: this
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#getMultipartParameters
  signature:
    return: java.util.Map
  copy:
  - from:
    - this
    - .org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#multipartFiles#java.util.Map
    to: result
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#getMultipartFiles
  signature:
    return: org.springframework.util.MultiValueMap
  copy:
  - from:
    - this
    - .org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#multipartParameters#org.springframework.util.MultiValueMap
    to: result
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#getMultipartFiles
  copy:
  - from:
    - this
    - .org.springframework.web.multipart.commons.CommonsFileUploadSupport$MultipartParsingResult#<rule-storage>#java.lang.Object
    to: result
- function: org.springframework.web.multipart.commons.CommonsFileUploadSupport#parseFileItems
  taintCopyOnly: true
  copy:
  - from: arg(0)
    to: result
