package org.opentaint.ir.impl.features.classpaths

import kotlinx.metadata.InconsistentKotlinMetadataException
import kotlinx.metadata.KmConstructor
import kotlinx.metadata.KmFunction
import kotlinx.metadata.KmProperty
import kotlinx.metadata.KmTypeParameter
import kotlinx.metadata.jvm.KotlinClassHeader
import kotlinx.metadata.jvm.KotlinClassMetadata
import org.opentaint.ir.api.jvm.JIRClassExtFeature
import org.opentaint.ir.api.jvm.JIRClassOrInterface
import org.opentaint.ir.api.jvm.ext.annotation
import org.opentaint.ir.impl.bytecode.logger

object KotlinMetadata : JIRClassExtFeature {

    const val METADATA_KEY = "kotlinClassMetadata"

    override fun extensionValuesOf(clazz: JIRClassOrInterface): Map<String, Any>? {
        val kMetadata = clazz.kMetadata
        if (kMetadata != null) {
            return mapOf(METADATA_KEY to KotlinMetadataHolder(kMetadata))
        }

        return null
    }

    /**
     * Returns [KotlinClassMetadata] instance for the class if it was generated by Kotlin.
     * See docs for [Metadata] for more info on how it is represented in bytecode and what it contains.
     */
    @Suppress("UNCHECKED_CAST")
    private val JIRClassOrInterface.kMetadata: KotlinClassMetadata?
        get() {
            val kmParameters = annotation("kotlin.Metadata")?.values ?: return null
            val kmHeader = KotlinClassHeader(
                kmParameters["k"] as? Int,
                (kmParameters["mv"] as? List<Int>)?.toIntArray(),
                (kmParameters["d1"] as? List<String>)?.toTypedArray(),
                (kmParameters["d2"] as? List<String>)?.toTypedArray(),
                kmParameters["xs"] as? String,
                kmParameters["pn"] as? String,
                kmParameters["xi"] as? Int,
            )
            return try {
                KotlinClassMetadata.read(kmHeader)
            } catch (e: InconsistentKotlinMetadataException) {
                logger.warn {
                    "Can't parse Kotlin metadata annotation found on class $name, the class may be damaged"
                }
                null
            }
        }

}

class KotlinMetadataHolder(meta: KotlinClassMetadata) {

    val functions: List<KmFunction> = when (meta) {
        is KotlinClassMetadata.Class -> meta.toKmClass().functions
        is KotlinClassMetadata.FileFacade -> meta.toKmPackage().functions
        is KotlinClassMetadata.MultiFileClassPart -> meta.toKmPackage().functions
        else -> listOf()
    }

    val constructors: List<KmConstructor> =
        (meta as? KotlinClassMetadata.Class)?.toKmClass()?.constructors ?: emptyList()

    val properties: List<KmProperty> = when (meta) {
        is KotlinClassMetadata.Class -> meta.toKmClass().properties
        is KotlinClassMetadata.FileFacade -> meta.toKmPackage().properties
        is KotlinClassMetadata.MultiFileClassPart -> meta.toKmPackage().properties
        else -> listOf()
    }

    val kmTypeParameters: List<KmTypeParameter>? =
        (meta as? KotlinClassMetadata.Class)?.toKmClass()?.typeParameters

}
