package org.opentaint.ir.impl.features.classpaths

import mu.KLogging
import org.opentaint.ir.api.jvm.JIRClassExtFeature
import org.opentaint.ir.api.jvm.JIRClassOrInterface
import org.opentaint.ir.api.jvm.ext.annotation
import kotlin.metadata.KmConstructor
import kotlin.metadata.KmFunction
import kotlin.metadata.KmProperty
import kotlin.metadata.KmTypeParameter
import kotlin.metadata.jvm.KotlinClassMetadata

object KotlinMetadata : JIRClassExtFeature {

    const val METADATA_KEY = "kotlinClassMetadata"

    private val logger = object : KLogging() {}.logger

    // avoid multiple reports of the same issue
    private var failureReported = false

    override fun extensionValuesOf(clazz: JIRClassOrInterface): Map<String, Any>? {
        runCatching {
            val kMetadata = clazz.kMetadata
            if (kMetadata != null) {
                return mapOf(METADATA_KEY to KotlinMetadataHolder(kMetadata))
            }
        }.onFailure { ex ->
            if (!failureReported) {
                failureReported = true
                logger.error(ex) { "Failed to load kotlin class metadata" }
            }
        }

        return null
    }

    /**
     * Returns [KotlinClassMetadata] instance for the class if it was generated by Kotlin.
     * See docs for [Metadata] for more info on how it is represented in bytecode and what it contains.
     */
    @Suppress("UNCHECKED_CAST")
    private val JIRClassOrInterface.kMetadata: KotlinClassMetadata?
        get() {
            val kmParameters = annotation("kotlin.Metadata")?.values ?: return null
            val metadata = kotlin.metadata.jvm.Metadata(
                kmParameters["k"] as? Int,
                (kmParameters["mv"] as? List<Int>)?.toIntArray(),
                (kmParameters["d1"] as? List<String>)?.toTypedArray(),
                (kmParameters["d2"] as? List<String>)?.toTypedArray(),
                kmParameters["xs"] as? String,
                kmParameters["pn"] as? String,
                kmParameters["xi"] as? Int,
            )
            return KotlinClassMetadata.readStrict(metadata)
        }

}

class KotlinMetadataHolder(meta: KotlinClassMetadata) {

    val functions: List<KmFunction> = when (meta) {
        is KotlinClassMetadata.Class -> meta.kmClass.functions
        is KotlinClassMetadata.FileFacade -> meta.kmPackage.functions
        is KotlinClassMetadata.MultiFileClassPart -> meta.kmPackage.functions
        else -> listOf()
    }

    val constructors: List<KmConstructor> =
        (meta as? KotlinClassMetadata.Class)?.kmClass?.constructors ?: emptyList()

    val properties: List<KmProperty> = when (meta) {
        is KotlinClassMetadata.Class -> meta.kmClass.properties
        is KotlinClassMetadata.FileFacade -> meta.kmPackage.properties
        is KotlinClassMetadata.MultiFileClassPart -> meta.kmPackage.properties
        else -> listOf()
    }

    val kmTypeParameters: List<KmTypeParameter>? =
        (meta as? KotlinClassMetadata.Class)?.kmClass?.typeParameters
}
