package org.opentaint.ir.analysis.impl

import org.opentaint.ir.analysis.AnalysisEngine
import org.opentaint.ir.analysis.JIRNaivePoints2EngineFactory
import org.opentaint.ir.analysis.JIRSimplifiedGraphFactory
import org.opentaint.ir.analysis.UnusedVariableAnalysisFactory
import org.opentaint.ir.analysis.analyzers.UnusedVariableAnalyzer
import org.opentaint.ir.impl.features.InMemoryHierarchy
import org.opentaint.ir.impl.features.Usages
import org.opentaint.ir.testing.WithDB
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import java.util.*
import java.util.stream.Stream

class UnusedVariableTest : BaseAnalysisTest() {
    companion object : WithDB(Usages, InMemoryHierarchy) {
        @JvmStatic
        fun provideClassesForJuliet563(): Stream<Arguments> = provideClassesForJuliet(563, listOf(
            // Unused variables are already optimized out by cfg
            "unused_uninit_variable_", "unused_init_variable_int", "unused_init_variable_long", "unused_init_variable_String_",

            // Unused variable is generated by cfg (!!)
            "unused_value_StringBuilder_17",

            // Expected answers are strange, seems to be problem in tests
            "_12",
        ))

        private val vulnerabilityType = UnusedVariableAnalyzer.value
    }

    @ParameterizedTest
    @MethodSource("provideClassesForJuliet563")
    fun `test on Juliet's CWE 563`(className: String) {
        testSingleJulietClass(engine, vulnerabilityType, className)
    }

    private val engine: AnalysisEngine
        get() {
            val graph = JIRSimplifiedGraphFactory().createGraph(cp)
            val points2Engine = JIRNaivePoints2EngineFactory.createPoints2Engine(graph)
            return UnusedVariableAnalysisFactory().createAnalysisEngine(graph, points2Engine)
        }
}