/*
 * This file is generated by jOOQ.
 */
package org.opentaint.ir.impl.storage.jooq.tables

import org.opentaint.ir.impl.storage.jooq.tables.records.AnnotationsRecord
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Annotations(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AnnotationsRecord>?,
    aliased: Table<AnnotationsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AnnotationsRecord>(
    alias,
    org.opentaint.ir.impl.storage.jooq.DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>Annotations</code>
         */
        val ANNOTATIONS = org.opentaint.ir.impl.storage.jooq.tables.Annotations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AnnotationsRecord> = AnnotationsRecord::class.java

    /**
     * The column <code>Annotations.id</code>.
     */
    val ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.annotation_name</code>.
     */
    val ANNOTATION_NAME: TableField<AnnotationsRecord, Long?> = createField(DSL.name("annotation_name"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>Annotations.visible</code>.
     */
    val VISIBLE: TableField<AnnotationsRecord, Boolean?> = createField(DSL.name("visible"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>Annotations.parent_annotation</code>.
     */
    val PARENT_ANNOTATION: TableField<AnnotationsRecord, Long?> = createField(DSL.name("parent_annotation"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.class_id</code>.
     */
    val CLASS_ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("class_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.method_id</code>.
     */
    val METHOD_ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("method_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.field_id</code>.
     */
    val FIELD_ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("field_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.param_id</code>.
     */
    val PARAM_ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("param_id"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<AnnotationsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AnnotationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>Annotations</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>Annotations</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>Annotations</code> table reference
     */
    constructor(): this(DSL.name("Annotations"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AnnotationsRecord>): this(Internal.createPathAlias(child, key), child, key,
        org.opentaint.ir.impl.storage.jooq.tables.Annotations.Companion.ANNOTATIONS, null)
    override fun getSchema(): Schema = org.opentaint.ir.impl.storage.jooq.DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<AnnotationsRecord> = org.opentaint.ir.impl.storage.jooq.keys.PK_ANNOTATIONS
    override fun getKeys(): List<UniqueKey<AnnotationsRecord>> = listOf(org.opentaint.ir.impl.storage.jooq.keys.PK_ANNOTATIONS)
    override fun getReferences(): List<ForeignKey<AnnotationsRecord, *>> = listOf(
        org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_SYMBOLS_1,
        org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_ANNOTATIONS_1,
        org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_CLASSES_1,
        org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_METHODS_1,
        org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_FIELDS_1,
        org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_METHODPARAMETERS_1
    )

    private lateinit var _symbols: org.opentaint.ir.impl.storage.jooq.tables.Symbols
    private lateinit var _annotations: org.opentaint.ir.impl.storage.jooq.tables.Annotations
    private lateinit var _classes: org.opentaint.ir.impl.storage.jooq.tables.Classes
    private lateinit var _methods: org.opentaint.ir.impl.storage.jooq.tables.Methods
    private lateinit var _fields_: org.opentaint.ir.impl.storage.jooq.tables.Fields
    private lateinit var _methodparameters: org.opentaint.ir.impl.storage.jooq.tables.Methodparameters
    fun symbols(): org.opentaint.ir.impl.storage.jooq.tables.Symbols {
        if (!this::_symbols.isInitialized)
            _symbols = org.opentaint.ir.impl.storage.jooq.tables.Symbols(
                this,
                org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_SYMBOLS_1
            )

        return _symbols;
    }
    fun annotations(): org.opentaint.ir.impl.storage.jooq.tables.Annotations {
        if (!this::_annotations.isInitialized)
            _annotations = org.opentaint.ir.impl.storage.jooq.tables.Annotations(
                this,
                org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_ANNOTATIONS_1
            )

        return _annotations;
    }
    fun classes(): org.opentaint.ir.impl.storage.jooq.tables.Classes {
        if (!this::_classes.isInitialized)
            _classes = org.opentaint.ir.impl.storage.jooq.tables.Classes(
                this,
                org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_CLASSES_1
            )

        return _classes;
    }
    fun methods(): org.opentaint.ir.impl.storage.jooq.tables.Methods {
        if (!this::_methods.isInitialized)
            _methods = org.opentaint.ir.impl.storage.jooq.tables.Methods(
                this,
                org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_METHODS_1
            )

        return _methods;
    }
    fun fields_(): org.opentaint.ir.impl.storage.jooq.tables.Fields {
        if (!this::_fields_.isInitialized)
            _fields_ = org.opentaint.ir.impl.storage.jooq.tables.Fields(
                this,
                org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_FIELDS_1
            )

        return _fields_;
    }
    fun methodparameters(): org.opentaint.ir.impl.storage.jooq.tables.Methodparameters {
        if (!this::_methodparameters.isInitialized)
            _methodparameters = org.opentaint.ir.impl.storage.jooq.tables.Methodparameters(
                this,
                org.opentaint.ir.impl.storage.jooq.keys.FK_ANNOTATIONS_METHODPARAMETERS_1
            )

        return _methodparameters;
    }
    override fun `as`(alias: String): org.opentaint.ir.impl.storage.jooq.tables.Annotations =
        org.opentaint.ir.impl.storage.jooq.tables.Annotations(DSL.name(alias), this)
    override fun `as`(alias: Name): org.opentaint.ir.impl.storage.jooq.tables.Annotations =
        org.opentaint.ir.impl.storage.jooq.tables.Annotations(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): org.opentaint.ir.impl.storage.jooq.tables.Annotations =
        org.opentaint.ir.impl.storage.jooq.tables.Annotations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): org.opentaint.ir.impl.storage.jooq.tables.Annotations =
        org.opentaint.ir.impl.storage.jooq.tables.Annotations(name, null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Long?, Long?, Boolean?, Long?, Long?, Long?, Long?, Long?> = super.fieldsRow() as Row8<Long?, Long?, Boolean?, Long?, Long?, Long?, Long?, Long?>
}
