name: Check Symbols

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Check:
    runs-on: [self-hosted, ex44]
    container: buildpack-deps:noble-scm

    steps:
      - name: Checkout repo with actions
        uses: actions/checkout@v4
        with:
          repository: explyt/opentaint-mirroring
          ref: main
          token: ${{ secrets.SEQRA_GITHUB_TOKEN }}

      - name: Checkout original repo
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Transform
        uses: ./transform-repo
        with:
          repo-dir: repo

      - name: Run check-symbols
        uses: ./check-repo
        with:
          repo-dir: repo

      - name: Check license
        uses: ./check-license
        with:
          repo-dir: repo
          spdx: FSL-1.1-ALv2
