name: CI Analyzer

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - 'core/src/**'
      - 'core/build.gradle.kts'
      - 'core/settings.gradle.kts'
      - 'core/buildSrc/**'
      - 'core/gradle/**'
      - 'core/opentaint-java-querylang/**'
      - 'core/samples/**'
      - 'core/opentaint-ir/**'
      - 'core/opentaint-dataflow-core/**'
      - 'core/opentaint-configuration-rules/**'
      - 'core/opentaint-config/**'
      - 'core/opentaint-jvm-sast-dataflow/**'
      - 'core/opentaint-jvm-sast-project/**'
      - 'core/opentaint-jvm-sast-se-api/**'
      - 'core/opentaint-sast-test-util/**'
      - 'core/opentaint-utils/**'
      - 'core/opentaint-project-model/**'
      - 'core/opentaint-common-build/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'core/src/**'
      - 'core/build.gradle.kts'
      - 'core/settings.gradle.kts'
      - 'core/buildSrc/**'
      - 'core/gradle/**'
      - 'core/opentaint-java-querylang/**'
      - 'core/samples/**'
      - 'core/opentaint-ir/**'
      - 'core/opentaint-dataflow-core/**'
      - 'core/opentaint-configuration-rules/**'
      - 'core/opentaint-config/**'
      - 'core/opentaint-jvm-sast-dataflow/**'
      - 'core/opentaint-jvm-sast-project/**'
      - 'core/opentaint-jvm-sast-se-api/**'
      - 'core/opentaint-sast-test-util/**'
      - 'core/opentaint-utils/**'
      - 'core/opentaint-project-model/**'
      - 'core/opentaint-common-build/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RULES_VERSION: rules/v0.0.2
  EXPECTED_TRACES: 8785

jobs:
  check:
    runs-on: [ self-hosted, ex44 ]
    container: gitlab/gitlab-runner-helper:ubuntu-x86_64-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew check

      - name: Upload Gradle reports
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports-ci-basic
          path: '**/build/reports/'
          retention-days: 1

  owasp:
    if: false
    runs-on: [ self-hosted, ex44 ]
    container: gitlab/gitlab-runner-helper:ubuntu-x86_64-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: core

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build analyzer jar
        run: ./gradlew :projectAnalyzerJar

      - name: Build autobuilder jar
        run: ./gradlew opentaint-jvm-autobuilder:projectAutoBuilderJar

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout owasp
        uses: actions/checkout@v4
        with:
          repository: 'OWASP-Benchmark/BenchmarkJava'
          path: ./test-dir/OWASP

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.11'

      - name: Build owasp
        working-directory: .
        run: |
          java -jar core/opentaint-jvm-autobuilder/build/libs/opentaint-project-auto-builder.jar \
                    --project-root-dir test-dir/OWASP \
                    --build portable \
                    --result-dir test-dir/opentaint-project \
                    --logs-file test-dir/autobuild.log \
                    --verbosity debug

      - name: Download rules
        uses: robinraju/release-downloader@v1.12
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.SEQRA_GITHUB_TOKEN }}
          tag: ${{ env.RULES_VERSION }}
          fileName: opentaint-rules.tar.gz
          out-file-path: test-dir

      - name: Extract rules
        working-directory: .
        run: mkdir -p test-dir/opentaint-rules && tar xzf test-dir/opentaint-rules.tar.gz -C test-dir/opentaint-rules

      - name: Analyze owasp
        working-directory: .
        run: |
          java \
            -Dorg.opentaint.ir.impl.storage.defaultBatchSize=2000 \
            -Djdk.util.jar.enableMultiRelease=false \
            -Xmx8g \
            -jar core/build/libs/opentaint-project-analyzer.jar \
            --project test-dir/opentaint-project/project.yaml \
            --semgrep-rule-set test-dir/opentaint-rules \
            --output-dir test-dir/reports \
            --ifds-analysis-timeout=1000 \
            --logs-file test-dir/analyzer.log \
            --verbosity debug

      - name: Check report exists
        working-directory: .
        run: |
          if [ -e "test-dir/reports/report-ifds.sarif" ]; then
            echo "Report exists"
          else
            echo "Report does not exist"
            exit 1
          fi

      - name: Check stats
        working-directory: .
        run: |
          STATS="$(cat test-dir/analyzer.log | grep "TraceGenerationStats")"
          echo $STATS
          echo $STATS | grep -q "total=${{ env.EXPECTED_TRACES }}"
