name: CI Analyzer

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - 'core/src/**'
      - 'core/build.gradle.kts'
      - 'core/settings.gradle.kts'
      - 'core/buildSrc/**'
      - 'core/gradle/**'
      - 'core/opentaint-java-querylang/**'
      - 'core/samples/**'
      - 'core/opentaint-ir/**'
      - 'core/opentaint-dataflow-core/**'
      - 'core/opentaint-configuration-rules/**'
      - 'core/opentaint-config/**'
      - 'core/opentaint-jvm-sast-dataflow/**'
      - 'core/opentaint-jvm-sast-project/**'
      - 'core/opentaint-jvm-sast-se-api/**'
      - 'core/opentaint-sast-test-util/**'
      - 'core/opentaint-utils/**'
      - 'core/opentaint-project-model/**'
      - 'core/opentaint-common-build/**'
      - '.github/workflows/ci-analyzer.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'core/src/**'
      - 'core/build.gradle.kts'
      - 'core/settings.gradle.kts'
      - 'core/buildSrc/**'
      - 'core/gradle/**'
      - 'core/opentaint-java-querylang/**'
      - 'core/samples/**'
      - 'core/opentaint-ir/**'
      - 'core/opentaint-dataflow-core/**'
      - 'core/opentaint-configuration-rules/**'
      - 'core/opentaint-config/**'
      - 'core/opentaint-jvm-sast-dataflow/**'
      - 'core/opentaint-jvm-sast-project/**'
      - 'core/opentaint-jvm-sast-se-api/**'
      - 'core/opentaint-sast-test-util/**'
      - 'core/opentaint-utils/**'
      - 'core/opentaint-project-model/**'
      - 'core/opentaint-common-build/**'
      - '.github/workflows/ci-analyzer.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RULES_VERSION: rules/v0.0.2
  EXPECTED_TRACES: 8785

jobs:
  check:
    runs-on: ubuntu-latest
    container: gitlab/gitlab-runner-helper:ubuntu-x86_64-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew check

      - name: Upload Gradle reports
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports-ci-basic
          path: '**/build/reports/'
          retention-days: 1
