name: CI Autobuilder

on:
  workflow_dispatch:

  push:
    paths:
      - 'core/opentaint-jvm-autobuilder/**'
      - 'core/opentaint-project-model/**'
      - 'core/opentaint-utils/cli-util/**'
      - 'core/opentaint-common-build/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'core/opentaint-jvm-autobuilder/**'
      - 'core/opentaint-project-model/**'
      - 'core/opentaint-utils/cli-util/**'
      - 'core/opentaint-common-build/**'
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: [ self-hosted, ex44 ]
    container: gitlab/gitlab-runner-helper:ubuntu-x86_64-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: core

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build autobuilder jar
        run: ./gradlew opentaint-jvm-autobuilder:projectAutoBuilderJar

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout owasp
        uses: actions/checkout@v4
        with:
          repository: 'OWASP-Benchmark/BenchmarkJava'
          path: ./test-dir/OWASP

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.11'

      - name: Build owasp
        working-directory: .
        run: |
          java -jar core/opentaint-jvm-autobuilder/build/libs/opentaint-project-auto-builder.jar \
                    --project-root-dir test-dir/OWASP \
                    --build portable \
                    --result-dir test-dir/BenchmarkJava-portable-build \
                    --logs-file test-dir/autobuild.log \
                    --verbosity debug

      - name: Check build succeed
        working-directory: .
        run: |
          if [ -f "test-dir/BenchmarkJava-portable-build/project.yaml" ]; then
            exit 0
          else
            echo "Build failure"
            exit 1
          fi
