name: CI IR

on:
  workflow_dispatch:

  push:
    paths:
      - 'opentaint-core/opentaint-ir/**'
      - 'opentaint-core/opentaint-common-build/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'opentaint-core/opentaint-ir/**'
      - 'opentaint-core/opentaint-common-build/**'
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run core tests on JDK ${{ matrix.jdk }}
    runs-on: [ self-hosted, ex44 ]
    container: ubuntu:latest

    strategy:
      fail-fast: false
      matrix:
        jdk: [ 8, 11, 19 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'main' }}

      - name: Run tests
        run: ./gradlew opentaint-ir:check
        working-directory: opentaint-core

      - name: Upload Gradle reports
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports-jdk${{ matrix.jdk }}
          path: '**/build/reports/'
          retention-days: 1

  lifecycle:
    name: Run lifecycle tests
    runs-on: [ self-hosted, ex44 ]
    container: ubuntu:latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'main' }}

      - name: Run tests
        run: ./gradlew opentaint-ir:lifecycleTest
        working-directory: opentaint-core

      - name: Upload Gradle reports
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports-lifecycle
          path: '**/build/reports/'
          retention-days: 1
