name: Publish Autobuilder

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "CI Autobuilder" ]
    branches: [ main ]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: [ self-hosted, ex44 ]

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    container: cruizba/ubuntu-dind:focal-25.0.3
    permissions:
      contents: write
      packages: write

    steps:
      - name: Setup Git
        run: apt update && apt install -y git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for autobuilder changes
        id: changes
        uses: ./.github/actions/check-scoped-commits
        with:
          scopes: autobuilder,common
          tag-prefix: 'autobuilder/'

      - name: Set up JDK 8
        if: steps.changes.outputs.has-changes == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Set up Gradle
        if: steps.changes.outputs.has-changes == 'true'
        uses: gradle/actions/setup-gradle@v4

      - name: Build autobuilder jar
        if: steps.changes.outputs.has-changes == 'true'
        working-directory: opentaint-core
        run: ./gradlew opentaint-jvm-autobuilder:projectAutoBuilderJar -PanalyzerVersion=${{ steps.changes.outputs.version }}

      - name: Upload autobuilder jar
        if: steps.changes.outputs.has-changes == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: autobuilder/${{ steps.changes.outputs.version }}
          tag_name: autobuilder/${{ steps.changes.outputs.version }}
          body: ${{ steps.changes.outputs.release-notes }}
          files: opentaint-core/opentaint-jvm-autobuilder/build/libs/opentaint-project-auto-builder.jar
          make_latest: false

      - name: Update floating latest tag
        if: steps.changes.outputs.has-changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -f "autobuilder/latest"
          git push origin "autobuilder/latest" --force
